//Aircraft Spawn
airspawn setObjectTexture [0, "\A3\Air_F_EPC\Plane_CAS_01\Data\UI\Plane_CAS_01_CA.paa"];
airspawn addAction ["<t size='1.5' shadow='2' color='#FFA000'>Deploy Air Vehicle</t> <img size='4' color='#FFA000' shadow='2' image='\A3\Air_F_EPC\Plane_CAS_01\Data\UI\Plane_CAS_01_CA.paa'/>", {[["helicopters","planes"], [
"RHS_MELB_AH6M_H",
"RHS_MELB_AH6M_L",
"RHS_MELB_AH6M_M",
"RHS_MELB_MH6M",
"RHS_MELB_MH6M",
"rhsusf_f22",
"RHS_A10_AT",
"RHS_A10",
"RHS_AH64D_wd_AA",
"RHS_AH64D_CS",
"RHS_AH64D_GS",
"RHS_AH64D",
"RHS_CH_47F",
"RHS_CH_47F_light",
"RHS_UH60M",
"RHS_UH60M_MEV2",
"RHS_UH60M_MEV",
"B_Heli_Light_01_armed_F",
"B_Heli_Light_01_F",
"B_Heli_Attack_01_F",
"B_Heli_Transport_03_F",
"B_Heli_Transport_03_unarmed_F",
"B_Heli_Transport_01_F",
"B_Heli_Transport_01_camo_F",
"RHS_UH1Y_FFAR",
"RHS_UH1Y",
"RHS_UH1Y_UNARMED",
"rhsusf_CH53E_USMC",
"RHS_AH1Z_CS",
"RHS_AH1Z_GS",
"RHS_AH1Z"
], "air_spawn"] execvm "ASORVS\open.sqf";}];
//Aircraft Spawn 2 
airspawn1 setObjectTexture [0, "\A3\Air_F_EPC\Plane_CAS_01\Data\UI\Plane_CAS_01_CA.paa"];
airspawn1 addAction ["<t size='1.5' shadow='2' color='#FFA000'>Deploy Air Vehicle</t> <img size='4' color='#FFA000' shadow='2' image='\A3\Air_F_EPC\Plane_CAS_01\Data\UI\Plane_CAS_01_CA.paa'/>", {[["helicopters","planes"], [
"RHS_MELB_AH6M_H",
"RHS_MELB_AH6M_L",
"RHS_MELB_AH6M_M",
"RHS_MELB_MH6M",
"RHS_MELB_MH6M",
"rhsusf_f22",
"RHS_A10_AT",
"RHS_A10",
"RHS_AH64D_wd_AA",
"RHS_AH64D_CS",
"RHS_AH64D_GS",
"RHS_AH64D",
"RHS_CH_47F",
"RHS_CH_47F_light",
"RHS_UH60M",
"RHS_UH60M_MEV2",
"RHS_UH60M_MEV",
"B_Heli_Light_01_armed_F",
"B_Heli_Light_01_F",
"B_Heli_Attack_01_F",
"B_Heli_Transport_03_F",
"B_Heli_Transport_03_unarmed_F",
"B_Heli_Transport_01_F",
"B_Heli_Transport_01_camo_F",
"RHS_UH1Y_FFAR",
"RHS_UH1Y",
"RHS_UH1Y_UNARMED",
"rhsusf_CH53E_USMC",
"RHS_AH1Z_CS",
"RHS_AH1Z_GS",
"RHS_AH1Z"
], "air_spawn_1"] execvm "ASORVS\open.sqf";}];