
//Init stuff
_crate = _this select 0;
["AmmoboxInit",[_crate,true,{true}]] spawn BIS_fnc_arsenal;

/*
_crate = _this select 0;
["AmmoboxInit",[_crate,false,{true}]] spawn BIS_fnc_arsenal;
 
//Lists of items to include
_availableHeadgear = [

// RHS Vehicle and Heli Helmets
	"rhsusf_hgu56p",
	"rhsusf_hgu56p_mask",
	"rhsusf_cvc_green_helmet",
	"rhsusf_cvc_green_ess",
	"RHS_jetpilot_usaf",

// RHS Boonies and beanies
	"rhsusf_patrolcap_ocp",
	"RHSUSF_PATROLCAP_UCP",
	"rhs_Booniehat_ocp",
	"rhs_Booniehat_m81",
	"RHSUSF_BOWMAN",
	"RHSUSF_BOWMAN_CAP",
	"RHS_BOONIEHAT_UCP",
	"RHS_BOONIEHAT_MARPATD",
	"RHS_BOONIEHAT_MARPATWD",
	
// RHS ACH Helmet
	"rhsusf_ach_helmet_headset_ess_ocp",
	"rhsusf_ach_helmet_ocp",
	"rhsusf_ach_helmet_ESS_ocp",
	"rhsusf_ach_helmet_headset_ocp",
	"rhsusf_ach_helmet_ocp",	
	"rhsusf_ach_helmet_ocp_norotos",	
	"rhsusf_ach_helmet_ucp",	
	"rhsusf_ach_helmet_ucp_norotos",	
	"rhsusf_ach_helmet_M81",	
	"rhsusf_ach_helmet_camo_ocp",
	"rhsusf_ach_helmet_headset_ocp",	
	"rhsusf_ach_helmet_headset_ucp",	
	"rhsusf_ach_helmet_ESS_ocp",	
	"rhsusf_ach_helmet_ESS_ucp",	
	"rhsusf_ach_helmet_headset_ess_ocp",	
	"rhsusf_ach_helmet_headset_ess_ucp",	
	"rhsusf_ach_bare",	
	"rhsusf_ach_bare_ess",	
	"rhsusf_ach_bare_headset",	
	"rhsusf_ach_bare_headset_ess",	
	"rhsusf_ach_bare_tan",	
	"rhsusf_ach_bare_tan_ess",	
	"rhsusf_ach_bare_tan_headset",	
	"rhsusf_ach_bare_tan_headset_ess",	
	"rhsusf_ach_bare_wood",	
	"rhsusf_ach_bare_wood_ess",	
	"rhsusf_ach_bare_wood_headset",	
	"rhsusf_ach_bare_wood_headset_ess",	
	"rhsusf_ach_bare_des",
	"rhsusf_ach_bare_des_ess",	
	"rhsusf_ach_bare_des_headset",	
	"rhsusf_ach_bare_des_headset_ess",	
	"rhsusf_ach_bare_semi",	
	"rhsusf_ach_bare_semi_ess",	
	"rhsusf_ach_bare_semi_headset",	
	"rhsusf_ach_bare_semi_headset_ess",	
	
// Ops Core Helmets
	"rhsusf_opscore_01",
	"rhsusf_opscore_01_tan",
	"rhsusf_opscore_02",	
	"rhsusf_opscore_02_tan",
	"rhsusf_opscore_03_ocp",
	"rhsusf_opscore_04_ocp",
	
// RHS MICH Helmet
	"rhsusf_mich_helmet_marpatwd",	
	"rhsusf_mich_helmet_marpatwd_headset",	
	"rhsusf_mich_helmet_marpatd",	
	"rhsusf_mich_helmet_marpatd_headset",	
	"rhsusf_mich_helmet_marpatwd_alt",	
	"rhsusf_mich_helmet_marpatwd_alt_headset",	
	"rhsusf_mich_helmet_marpatd_alt",	
	"rhsusf_mich_helmet_marpatd_alt_headset",	
	"rhsusf_mich_helmet_marpatwd_norotos",	
	"rhsusf_mich_helmet_marpatwd_norotos_headset",	
	"rhsusf_mich_helmet_marpatd_norotos",
	"rhsusf_mich_helmet_marpatd_norotos_headset",
	"rhsusf_mich_helmet_marpatwd_norotos_arc",	
	"rhsusf_mich_helmet_marpatwd_norotos_arc_headset",	
	"rhsusf_mich_helmet_marpatd_norotos_arc",
	"rhsusf_mich_helmet_marpatd_norotos_arc_headset",
	"rhsusf_mich_bare",	
	"rhsusf_mich_bare_headset",	
	"rhsusf_mich_bare_alt",	
	"rhsusf_mich_bare_norotos",	
	"rhsusf_mich_bare_norotos_headset",	
	"rhsusf_mich_bare_norotos_alt",	
	"rhsusf_mich_bare_norotos_alt_headset",	
	"rhsusf_mich_bare_norotos_arc",	
	"rhsusf_mich_bare_norotos_arc_headset",	
	"rhsusf_mich_bare_norotos_arc_alt",	
	"rhsusf_mich_bare_norotos_arc_alt_headset",	
	"rhsusf_mich_bare_tan",	
	"rhsusf_mich_bare_tan_headset",	
	"rhsusf_mich_bare_alt_tan",	
	"rhsusf_mich_bare_norotos_tan",	
	"rhsusf_mich_bare_norotos_tan_headset",	
	"rhsusf_mich_bare_norotos_alt_tan",	
	"rhsusf_mich_bare_norotos_alt_tan_headset",	
	"rhsusf_mich_bare_norotos_arc_tan",	
	"rhsusf_mich_bare_norotos_arc_tan_headset",	
	"rhsusf_mich_bare_norotos_arc_alt_tan",	
	"rhsusf_mich_bare_norotos_arc_alt_tan_headset",	
	"rhsusf_mich_bare_semi",	
	"rhsusf_mich_bare_semi_headset",	
	"rhsusf_mich_bare_alt_semi",	
	"rhsusf_mich_bare_norotos_semi",	
	"rhsusf_mich_bare_norotos_semi_headset",	
	"rhsusf_mich_bare_norotos_alt_semi",	
	"rhsusf_mich_bare_norotos_alt_semi_headset",	
	"rhsusf_mich_bare_norotos_arc_semi",
	"rhsusf_mich_bare_norotos_arc_semi_headset",	
	"rhsusf_mich_bare_norotos_arc_alt_semi",	
	"rhsusf_mich_bare_norotos_arc_alt_semi_headset",
	"RHSUSF_LWH_HELMET_MARPATD",
	"RHSUSF_LWH_HELMET_MARPATD_ESS",
	"RHSUSF_LWH_HELMET_MARPATD_HEADSET",
	"RHSUSF_LWH_HELMET_MARPATWD",
	"RHSUSF_LWH_HELMET_MARPATWD_ESS",
	"RHSUSF_LWH_HELMET_MARPATWD_HEADSET",
	"RHSUSF_LWH_HELMET_M1942",
	
	
//Vanilla Helmets / Hats
	"H_Booniehat_khk",
	"H_Booniehat_oli",
	"H_Booniehat_mcamo",
	"H_Booniehat_grn",
	"H_Booniehat_tan",
	"H_Booniehat_dirty",
	"H_Booniehat_indp",
	"H_Booniehat_khk_hs",
	"H_Cap_oli",
	"H_Cap_headphones",
	"H_Cap_tan",
	"H_Cap_blk",
	"H_Cap_tan_specops_US",
	"H_Cap_khaki_specops_UK",
	"H_Cap_oli_hs",
	"H_Cap_usblack",
	"H_Shemag_khk",
	"H_Shemag_tan",
	"H_Shemag_olive",
	"H_Shemag_olive_hs",
	"H_ShemagOpen_khk",
	"H_ShemagOpen_tan",
	"H_Beret_grn_SF",
	"H_Beret_blk",
	"H_Beret_red",
	"H_Beret_grn",
	"H_Beret_brn_SF",
	"H_Beret_02",
	"H_Watchcap_blk",
	"H_Watchcap_cbr",
	"H_Watchcap_khk",
	"H_Watchcap_camo",
	"H_Watchcap_sgg",

// ASCZ Helmets
	"H_HelmetSpecB",
	"H_HelmetSpecB_blk",
	"H_HelmetSpecB_paint2",
	"H_HelmetSpecB_sand",
	"H_HelmetSpecB_snakeskin",
	"H_HelmetB",
	"H_HelmetB_camo",
	"H_HelmetB_desert",
	"H_HelmetB_grass",
	"H_HelmetB_black",
	"H_HelmetB_sand",
	"H_HelmetB_snakeskin",
	"H_HelmetB_light",
	"H_HelmetB_light_black",
	"H_HelmetB_light_desert",
	"H_HelmetB_light_grass",
	"H_HelmetB_light_sand",
	"H_HelmetB_light_snakeskin"
];
 
_availableGoggles = [
	"G_Shades_Black",
	"G_Shades_Blue",
	"G_Shades_Green",
	"G_Shades_Red",
	"G_Spectacles_Tinted",
	"G_Lowprofile",
	"rhs_googles_clear",
	"rhs_googles_orange",
	"rhs_googles_yellow",
	"rhs_googles_black",
	"G_Diving",
	"G_Balaclava_blk",
	"G_Balaclava_combat",
	"G_Balaclava_lowprofile",
	"G_Balaclava_oli",
	"rhs_balaclava",
	"rhs_googles_black",
	"rhs_googles_clear",
	"rhs_googles_orange",
	"rhs_googles_yellow",
	"rhs_scarf",
	"G_Aviator",
	"G_Balaclava_shades",
	"G_Balaclava_sport",
	"G_Balaclava_tan",
	"G_Combat",
	"G_Squares",
	"G_Squares_Tinted",
	"G_Tactical_Black",
	"G_Tactical_Clear"
];
 
_availableUniforms = [

// ASCZ Uniforms
	"U_B_CombatUniform_wdl",
	"U_B_CombatUniform_wdl_tshirt",
	"U_B_CombatUniform_wdl_vest",
	"U_B_CombatUniform_sgg",
	"U_B_CombatUniform_sgg_tshirt",
	"U_B_CombatUniform_sgg_vest",
	"U_B_CombatUniform_NKPBlack_rollup",
	"U_B_CombatUniform_NKPBlack",
	"U_B_CombatUniform_NKPBlack_tshirt",
	"U_B_CombatUniform_NKPBlack_vest",
	"U_B_CombatUniform_NKPBlue_rollup",
	"U_B_CombatUniform_NKPBlue",
	"U_B_CombatUniform_NKPBlue_tshirt",
	"U_B_CombatUniform_NKPBlue_vest",
	"U_B_CombatUniform_NKPOlive_rollup",
	"U_B_CombatUniform_NKPOlive",
	"U_B_CombatUniform_NKPOlive_tshirt",
	"U_B_CombatUniform_NKPOlive_vest",
	"U_B_CombatUniform_NKPTan_rollup",
	"U_B_CombatUniform_NKPTan",
	"U_B_CombatUniform_NKPTan_tshirt",
	"U_B_CombatUniform_NKPTan_vest",
	"U_B_CombatUniform_NKPwdl",
	"U_B_CombatUniform_NKPwdl_tshirt",
	"U_B_CombatUniform_NKPwdl_vest",
	
// RHS Uniforms	
	"rhs_uniform_cu_ocp_101st",
	"rhs_uniform_FROG01_m81",
	"RHS_UNIFORM_FROG01_D",
	"RHS_UNIFORM_FROG01_WD",
	"rhs_uniform_cu_ucp_101st",

// Vanilla Uniforms
	"U_B_PilotCoveralls",
	"U_B_HeliPilotCoveralls",
	"U_B_Wetsuit",
	"U_B_GhillieSuit",
	"U_B_CombatUniform_mcam_tshirt",
	"U_B_CombatUniform_mcam",
	"U_B_CombatUniform_mcam_vest",
	"U_B_CombatUniform_mcam_worn",
	"U_B_SpecopsUniform_sgg",
	
// Vanilla Guerilla Uniforms
	"U_BG_Guerilla1_1",
	"U_BG_Guerilla2_1",
	"U_BG_Guerilla2_2",
	"U_BG_Guerilla2_3",
	"U_BG_Guerilla3_1",
	"U_BG_Guerilla3_2",
	"U_BG_Guerilla6_1",
	"U_BG_leader"
];

_availableVests = [

// ASCZ Vests
	"V_PlateCarrier1_oli",
	"V_PlateCarrier1_cbr",
	"V_PlateCarrier1_khk",
	"V_PlateCarrier2_oli",
	"V_PlateCarrier2_khk",
	"V_PlateCarrier2_cbr",
	"V_PlateCarrier2_blk",
	"V_PlateCarrierIA1_oli",
	"V_PlateCarrierIA1_khk",
	"V_PlateCarrierIA1_cbr",
	"V_PlateCarrierIA1_blk",
	"V_PlateCarrierIA2_oli",
	"V_PlateCarrierIA2_khk",
	"V_PlateCarrierIA2_cbr",
	"V_PlateCarrierIA2_blk",
	"V_Rangemaster_belt_oli",
	"V_Rangemaster_belt_khk",
	"V_Rangemaster_belt_cbr",
	"V_Rangemaster_belt_blk",
	"V_TacVest_blk_POLICE",
	"V_TacVestIR_cbr",
	"V_TacVestIR_khk",

// RHS Army Vests
	"rhsusf_iotv_ocp",
	"rhsusf_iotv_ocp_Repair",
	"rhsusf_iotv_ocp_Grenadier",
	"rhsusf_iotv_ocp_Medic",
	"rhsusf_iotv_ocp_Rifleman",
	"rhsusf_iotv_ocp_SAW",
	"rhsusf_iotv_ocp_Squadleader",
	"rhsusf_iotv_ocp_Teamleader",	
	"rhsusf_iotv_ucp",
	"rhsusf_iotv_ucp_Grenadier",	
	"rhsusf_iotv_ucp_Medic",	
	"rhsusf_iotv_ucp_Repair",	
	"rhsusf_iotv_ucp_Rifleman",	
	"rhsusf_iotv_ucp_SAW",	
	"rhsusf_iotv_ucp_Squadleader",	
	"rhsusf_iotv_ucp_Teamleader",
	
// RHS Marine Vests
	"rhsusf_spc",
	"rhsusf_spc_rifleman",
	"rhsusf_spc_iar",
	"rhsusf_spc_corpsman",
	"rhsusf_spc_crewman",
	"rhsusf_spc_light",
	"rhsusf_spc_marksman",
	"rhsusf_spc_mg",
	"rhsusf_spc_squadleader",
	"rhsusf_spc_teamleader",
	
// Vanilla Vests
	"V_RebreatherB",
	"V_Rangemaster_belt",
	"V_BandollierB_khk",
	"V_BandollierB_cbr",
	"V_BandollierB_rgr",
	"V_BandollierB_blk",
	"V_BandollierB_oli",
	"V_PlateCarrier1_rgr",
	"V_PlateCarrier2_rgr",
	"V_PlateCarrier3_rgr",
	"V_PlateCarrierGL_rgr",
	"V_PlateCarrier1_blk",
	"V_PlateCarrierSpec_rgr",
	"V_Chestrig_khk",
	"V_Chestrig_rgr",
	"V_Chestrig_blk",
	"V_Chestrig_oli",
	"V_TacVest_khk",
	"V_TacVest_brn",
	"V_TacVest_oli",
	"V_TacVest_blk",
	"V_TacVest_camo",
	"V_TacVestIR_blk",
	"V_TacVestCamo_khk",
	"V_PlateCarrier_Kerry",
	"V_PlateCarrierL_CTRG",
	"V_PlateCarrierH_CTRG",
	"V_PlateCarrierGL_blk",
	"V_PlateCarrierGL_mtp",
	"V_PlateCarrierSpec_blk",
	"V_PlateCarrierSpec_mtp",
	"V_PlateCarrierIAGL_oli"
];
 
_availableBackpacks = [
	"506th_assault_eagleaiii_coy_Medic",
	"B_Mortar_01_support_F",
	"B_Mortar_01_weapon_F",
	"B_Parachute",
	"tf_rt1523g_rhs",
	"tf_rt1523g_big_rhs",
	"B_AssaultPack_cbr",
	"B_AssaultPack_khk",
	"B_AssaultPack_rgr",
	"B_AssaultPack_blk",
	"B_AssaultPack_mcamo",
	"B_Kitbag_mcamo",
	"B_Kitbag_cbr",
	"B_Carryall_cbr",
	"B_Carryall_mcamo",
	"B_Carryall_khk",
	"B_Carryall_oli",
	"rhsusf_assault_eagleaiii_ucp",
	"rhsusf_assault_eagleaiii_ocp",
	"rhsusf_assault_eagleaiii_coy",
	"rhs_M170_Bipod_Bag",
	"rhs_M225_Gun_Bag",
	"RHS_M2_Gun_Bag",
	"RHS_M2_Tripod_Bag",
	"RHS_M2_MiniTripod_Bag",
	"RHS_Mk19_Gun_Bag",
	"RHS_Mk19_Tripod_Bag",
	"rhs_Tow_Gun_Bag",
	"rhs_TOW_Tripod_Bag"
];
 
_availableItems = [

	"rhsusf_ANPVS_14",
	"rhsusf_ANPVS_15",
	"rhsusf_ANPVS_14_full",
	"rhsusf_ANPVS_15_full",
	"rhsusf_ANPVS_14_oval",
	"rhsusf_ANPVS_14_full_ng",
	"rhsusf_ANPVS_14_oval_ng",
	"rhsusf_ANPVS_15_full_ng",
	"rhsusf_ANPVS_15_ng",
	"ItemWatch",
	"ItemCompass",
	"ItemGPS",
	"ItemMap",
	"ItemAndroid",
	"ToolKit",
	"ItemcTabHCam",
	"ItemcTab",
	"ItemMicroDAGR",
	"B_UavTerminal",
	"ACE_HuntIR_monitor",
	"ACE_M26_Clacker",
	"ACE_Clacker",
	"ACE_DefusalKit",
	"ACE_wirecutter",
	"ACE_EarPlugs",
	"ACE_CableTie",
	"ACE_MapTools",
	"ACE_Kestrel4500",
	"ACE_Altimeter",	
	"ACE_fieldDressing",
	"ACE_Morphine",
	"ACE_epinephrine",
	"ACE_bloodIV_250",
	"ACE_UAVBattery",
	"ACE_TacticalLadder_Item",
	"ACE_Tripod",
	"ACE_Flashlight_KSF1",
	"ACE_Flashlight_XL50",
	"ACE_Flashlight_MX991",
	"TIAD_506th_UAV_Item",
	"ACE_bodyBag",
	"MineDetector"
];

_availableAccessories = [

// RHS Attachments
	"rhsusf_acc_anpeq15",
	"rhsusf_acc_anpeq15_light",
	"rhsusf_acc_anpeq15A",
	"rhsusf_acc_anpeq15side",
	"rhsusf_acc_LEUPOLDMK4_2",
	"rhsusf_acc_ACOG",
	"rhsusf_acc_ACOG2",
	"rhsusf_acc_ACOG3",
	"rhsusf_acc_compm4",
	"rhsusf_acc_ELCAN",
	"rhsusf_acc_LEUPOLDMK4",
	"rhsusf_acc_SF3P556",
	"rhsusf_acc_harris_bipod",
	"rhsusf_acc_M2010S",
	"rhsusf_acc_SR25S",
	"rhsusf_acc_rotex5_grey",
	"rhsusf_acc_rotex5_tan",
	"rhsusf_acc_nt4_black",
	"rhsusf_acc_nt4_tan",
	"rhsusf_acc_muzzleFlash_SF",
	"rhsusf_acc_SFMB556",
	"rhsusf_acc_eotech_552",
	"rhsusf_acc_ELCAN_ard",
	"rhsusf_acc_ELCAN_pip",
	"rhsusf_acc_ACOG_wd",
	"rhsusf_acc_ACOG_d",
	"rhsusf_acc_ACOG_sa",
	"rhsusf_acc_ACOG_pip",
	"rhsusf_acc_ACOG_USMC",
	"rhsusf_acc_ACOG2_USMC",
	"rhsusf_acc_ACOG3_USMC",
	"rhsusf_acc_EOTECH",
	"rhsusf_acc_M2A1",
	"tf47_optic_m3maaws",
	
// Vanilla Attachments
	"optic_SOS",
	"optic_DMS",
	"optic_LRPS",
	"optic_MRCO",
	"bipod_01_F_snd",
	"bipod_01_F_blk",
	"bipod_01_F_mtp",
	"optic_Arco",
	"optic_Hamr",
	"optic_tws",
	"optic_tws_mg",
	"acc_flashlight",
	"Item_muzzle_snds_M",
	"Item_muzzle_snds_acp",
	"Item_muzzle_snds_B",
	"Item_optic_DMS",
	"Item_optic_LRPS",
	"muzzle_snds_L",
	"optic_Holosight_smg",
	"optic_ACO_grn_smg",
	
	
// ACE Weapons
	"ACE_acc_pointer_red",
	"ACE_acc_pointer_green",
	"acc_pointer_IR",
	"ACE_acc_pointer_green_IR",
	"ACE_optic_Arco_2D",
	"ACE_optic_Arco_PIP",
	"ACE_optic_LRPS_2D",
	"ACE_optic_LRPS_PIP",
	"ACE_optic_SOS_2D",
	"ACE_optic_SOS_PIP",
	"ACE_optic_MRCO_2D",
	"ACE_optic_MRCO_PIP",
	"ACE_optic_Hamr_2D",
	"ACE_optic_Hamr_PIP",
	
// FHQ Attachments
	"FHQ_optic_AimM_BLK",
	"FHQ_optic_HWS_G33",
	"FHQ_optic_HWS",
	"FHQ_optic_AC11704",
	"FHQ_optic_TWS3050",
	"FHQ_optic_MCCO_M_TAN",
	"FHQ_optic_MCCO_M_BLK",
	"FHQ_optic_AimM_TAN",
	"FHQ_optic_MARS_tan",
	"FHQ_optic_MARS",
	"FHQ_optic_AC12136_tan",
	"FHQ_optic_AC12136",
	"FHQ_optic_AC11704_tan",
	"FHQ_optic_LeupoldERT_tan",
	"FHQ_optic_VCOG_tan",
	"FHQ_optic_VCOG",
	"FHQ_acc_LLM01F",
	"FHQ_acc_LLM01L",
	"FHQ_acc_ANPEQ15_black",
	"FHQ_acc_ANPEQ15",
	"FHQ_optic_LeupoldERT",
	"FHQ_optic_MicroCCO_low_tan",
	"FHQ_optic_MicroCCO_low",
	"FHQ_optic_MicroCCO_tan",
	"FHQ_optic_MicroCCO",
	"FHQ_optic_HWS_G33_tan",
	"FHQ_optic_AIM_tan",
	"FHQ_optic_HWS_tan",
	"FHQ_optic_AIM",
	"FHQ_optic_ACOG_tan",
	"FHQ_optic_ACOG",
	
// DLC Accessories
	
	"optic_AMS",
	"optic_AMS_khk",
	"optic_AMS_snd",
	"optic_KHS_blk",
	"optic_KHS_old",
	"optic_KHS_tan",
	"muzzle_snds_338_black",
	"muzzle_snds_338_green",
	"muzzle_snds_338_sand",
	"muzzle_snds_93mmg",
	"muzzle_snds_93mmg_tan",
	
// RH Pistol Attachments
	"RH_demz",
	"optic_Yorris",
	"RH_gemtech9",
	"RH_A26",
	"RH_suppr9",
	"RH_aacusp",
	"RH_gemtech45",
	"RH_osprey",
	"RH_fhusp",
	"RH_x2",
	"RH_m6x",
	"RH_x300",
	"RH_pmsd",
	"RH_pmir",
	"RH_matchsd",
	"RH_m9qd",
	"RH_vp70stock",
	"RH_docter",
	"optic_MRD",
	"RH_sfn57",
	"RH_tecsd",
	"RH_muzisd"
	
];
 
_availableMagazines = [
// Rifles
	"30Rnd_556x45_Stanag",
	"rhs_mag_30Rnd_556x45_Mk318_Stanag",
	"30Rnd_556x45_Stanag_Tracer_Red",
	
// Shotguns
	"rhsusf_5Rnd_00Buck",
	"rhsusf_8Rnd_00Buck",
	"rhsusf_8Rnd_Slug",
	"rhsusf_5Rnd_Slug",
	
// LMGs
	"rhs_200rnd_556x45_M_SAW",
	"rhs_200rnd_556x45_T_SAW",
	"rhs_200rnd_556x45_B_SAW",
	"rhs_mag_762x51_M240_200",
	"rhsusf_100Rnd_556x45_soft_pouch",
	"rhsusf_100Rnd_762x51",
	"rhsusf_100Rnd_762x51_m993",
	"rhsusf_100Rnd_762x51_m61_ap",
	
// RH Pistol mags
	"RH_15Rnd_9x19_M9",
	"RH_7Rnd_50_AE",
	"RH_16Rnd_9x19_cz",
	"RH_14Rnd_9x19_sw",
	"RH_12Rnd_45cal_usp",
	"RH_8Rnd_9x18_Mak",
	"RH_7Rnd_45cal_m1911",
	"RH_16Rnd_40cal_usp",
	"RH_20Rnd_32cal_vz61",
	"RH_33Rnd_9x19_g18",
	"RH_17Rnd_9x19_g17",
	"RH_8Rnd_762_tt33",
	"RH_10Rnd_22LR_mk2",
	"RH_15Rnd_9x19_SIG",
	"RH_18Rnd_9x19_VP",
	"RH_6Rnd_44_Mag",
	"RH_6Rnd_357_Mag",
	"RH_6Rnd_454_Mag",
	"RH_6Rnd_45ACP_Mag",
	"RH_15Rnd_45cal_fnp",
	"RH_20Rnd_57x28_FN",
	"RH_18Rnd_9x19_gsh",
	"RH_32Rnd_9x19_tec",
	"RH_30Rnd_9x19_UZI",
	
// Underslung Grenades
	"rhs_mag_M433_HEDP",
	"rhs_mag_M441_HE",
	"rhs_mag_M4009",
	"rhs_mag_m576",
	"rhs_mag_M585_white",
	"rhs_mag_M661_green",
	"rhs_mag_M662_red",
	"rhs_mag_M713_red",
	"rhs_mag_M714_white",
	"rhs_mag_M715_green",
	"rhs_mag_M716_yellow",
	"rhsusf_mag_6Rnd_M441_HE",
	"rhsusf_mag_6Rnd_M433_HEDP",
	"rhsusf_mag_6Rnd_M714_white",
	"rhsusf_mag_6Rnd_M576_Buckshot",

// Snipers
	"rhsusf_20Rnd_762x51_m118_special_Mag",
	
// Launchers
	"rhs_fim92_mag",
	"tf47_m3maaws_heat",
	"tf47_m3maaws_hedp",
	"tf47_m3maaws_he",
	"tf47_m3maaws_smoke",
	"tf47_m3maaws_illum",
	"rhs_m136_mag",
	"rhs_m136_hp_mag",
	"rhs_m136_hedp_mag",
	"rhs_fgm148_magazine_AT",
	"rhs_mag_smaw_HEAA",
	"rhs_mag_smaw_HEDP",
	
// DLC Ammo
	"10Rnd_127x54_Mag",
	"10Rnd_93x64_DMR_05_Mag",
	"10Rnd_338_Mag",
	"20Rnd_762x51_Mag",
	"150Rnd_93x64_Mag",
	"130Rnd_338_Mag",
	
// Misc Equipment
	"ACE_HuntIR_M203", "20Rnd_556x45_UW_mag", "30Rnd_9x21_Mag"
];

_availableGrenades = [ 
	"DemoCharge_Remote_Mag", "SatchelCharge_Remote_Mag", "ClaymoreDirectionalMine_Remote_Mag",
	"SmokeShell", "SmokeShellRed", "SmokeShellGreen", "SmokeShellYellow", 
	"SmokeShellPurple", "SmokeShellBlue", "SmokeShellOrange",
	"ACE_HandFlare_Green", "ACE_HandFlare_Red", "ACE_HandFlare_White", "ACE_HandFlare_Yellow",
	"rhs_mag_mk84",
	"HandGrenade",
	"Chemlight_green", "Chemlight_red", "Chemlight_blue", "Chemlight_yellow",
	"B_IR_Grenade"
];

_availableWeapons = [
//M-16s
	"rhs_weap_m16a4",	
	"rhs_weap_m16a4_carryhandle",
	"rhs_weap_m16a4_carryhandle_pmag",	
	"rhs_weap_m16a4_bipod",	
	"rhs_weap_m16a4_carryhandle_bipod",	
	"rhs_weap_m16a4_grip",	
	"rhs_weap_m16a4_carryhandle_grip",	
	"rhs_weap_m16a4_carryhandle_grip_pmag",
	"rhs_weap_m16a4_carryhandle_M203",
	
// M4A1s
	"rhs_weap_m4a1",
	"rhs_weap_m4a1_grip",
	"rhs_weap_m4a1_grip2",
	"rhs_weap_m4a1_m320",
	"rhs_weap_m4a1_carryhandle",
	"rhs_weap_m4a1_carryhandle_grip",
	"rhs_weap_m4a1_carryhandle_grip2",
	"rhs_weap_m4a1_carryhandle_pmag",
	
//MK 18 Block I
	"rhs_weap_mk18",
	"rhs_weap_mk18_grip2",
	"rhs_weap_mk18_grip2_KAC",
	"rhs_weap_mk18_KAC",
	"rhs_weap_mk18_m320",
	
// M4A1 Block IIs
	"rhs_weap_m4a1_blockII",
	"rhs_weap_m4a1_blockII_grip2",
	"rhs_weap_m4a1_blockII_grip2_KAC",
	"rhs_weap_m4a1_blockII_KAC",
	"rhs_weap_m4a1_blockII_M203",
	
// Sniper Rifles and DMRs
	"rhs_weap_sr25",
	"rhs_weap_sr25_ec",
	"rhs_weap_XM2010",
	"rhs_weap_XM2010_wd",
	"rhs_weap_XM2010_d",
	"rhs_weap_XM2010_sa",
	"rhs_weap_m14ebrri",
	
// 249s, 240s and IARs
	"rhs_weap_m240B_CAP",
	"rhs_weap_m249_pip",
	"rhs_weap_m249_pip_S",
	"rhs_weap_m249_pip_S_para",
	"rhs_weap_m249_pip_S_vfg",
	"rhs_weap_m249_pip_L",
	"rhs_weap_m249_pip_L_para",
	"rhs_weap_m249_pip_L_vfg",
	"rhs_weap_m27iar",

// Shotguns
	"rhs_weap_M590_8RD",
	"rhs_weap_M590_5RD",
	
// Launchers
	"tf47_m3maaws",
	"rhs_weap_M136",
	"rhs_weap_M136_hedp",
	"rhs_weap_M136_hp",
	"rhs_weap_fgm148",
	"rhs_weap_fim92",
	"rhs_weap_m32",
	"rhs_weap_M320",
	"rhs_weap_smaw",
	
// RH Pistols
	"RH_m9",
	"RH_deagle",
	"RH_deagleg",
	"RH_deagles",
	"RH_deaglem",
	"RH_cz75",
	"RH_sw659",
	"RH_usp",
	"RH_mak",
	"RH_m1911",
	"RH_kimber",
	"RH_kimber_nw",
	"RH_uspm",
	"RH_m9c",
	"RH_vz61",
	"RH_g18",
	"RH_g17",
	"RH_tt33",
	"RH_mk2",
	"RH_p226",
	"RH_p226s",
	"RH_g19",
	"RH_g19t",
	"RH_vp70",
	"RH_mateba",
	"RH_python",
	"RH_mp412",
	"RH_bull",
	"RH_bullb",
	"RH_ttracker",
	"RH_ttracker_g",
	"RH_fnp45",
	"RH_fnp45t",
	"RH_fn57",
	"RH_fn57_g",
	"RH_fn57_t",
	"RH_gsh18",
	"RH_tec9",
	"RH_muzi",
	"hgun_PDW2000_F",
	
// DLC Weapons
	"srifle_DMR_04_F", //10Rnd_127x54_Mag
	"srifle_DMR_04_Tan_F", //10Rnd_127x54_Mag
	"srifle_DMR_05_blk_F", //10Rnd_93x64_DMR_05_Mag
	"srifle_DMR_05_hex_F", //10Rnd_93x64_DMR_05_Mag
	"srifle_DMR_05_tan_f", //10Rnd_93x64_DMR_05_Mag
	"srifle_DMR_02_F", //10Rnd_338_Mag
	"srifle_DMR_02_camo_F", //10Rnd_338_Mag
	"srifle_DMR_02_sniper_F", //10Rnd_338_Mag
	"srifle_DMR_03_F", //20Rnd_762x51_Mag
	"srifle_DMR_03_multicam_F", //20Rnd_762x51_Mag
	"srifle_DMR_03_khaki_F", //20Rnd_762x51_Mag
	"srifle_DMR_03_tan_F", //20Rnd_762x51_Mag
	"srifle_DMR_03_woodland_F", //20Rnd_762x51_Mag
	"srifle_DMR_06_camo_F", //20Rnd_762x51_Mag
	"srifle_DMR_06_olive_F", //20Rnd_762x51_Mag
	"MMG_01_hex_F", //150Rnd_93x64_Mag
	"MMG_01_tan_F", //150Rnd_93x64_Mag
	"MMG_02_black_F", //130Rnd_338_Mag
	"MMG_02_camo_F", //130Rnd_338_Mag
	"MMG_02_sand_F", //130Rnd_338_Mag
	
// Misc Items
	"Binocular",
	"arifle_SDAR_F",
	"SMG_02_F"
];
 
// Populate with predefined items and whatever is already in the crate
[_crate,((backpackCargo _crate) + _availableBackpacks)] call BIS_fnc_addVirtualBackpackCargo;
[_crate,((itemCargo _crate) + _availableHeadgear + _availableGoggles + _availableUniforms + _availableVests + _availableItems + _availableAccessories)] call BIS_fnc_addVirtualItemCargo;
[_crate,((magazineCargo _crate) + _availableMagazines + _availableGrenades)] call BIS_fnc_addVirtualMagazineCargo;
[_crate,((weaponCargo _crate) + _availableWeapons)] call BIS_fnc_addVirtualWeaponCargo;
*/